[package]
name = "led_matrix_control"
version = "0.1.0"
authors = ["Sergey Cheremisov <q.basic60@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hidapi = "^1.2.3"
thiserror = "^1.0.20"
image = "^0.23.8"